licencie_connexion:
    path: /
    defaults:
        _controller: CTTCriteriumBundle:Licencie:connexion
        
licencie_validation:
    path: /validation/{licence}-{tour}
    defaults:
        _controller: CTTCriteriumBundle:Licencie:validation
    requirements:
        licence: '\d+'
        tour: '\d'
        
licencie_traitement:
    path: /traitement
    defaults:
        _controller: CTTCriteriumBundle:Licencie:traitement
        
admin_dashboard:
    path: /admin8052917
    defaults:
        _controller: CTTCriteriumBundle:Admin:dashboard
        
admin_export:
    path: /admin8052917/export-csv
    defaults:
        _controller: CTTCriteriumBundle:Admin:export